refactor: additional notification types
ArkEcosystem/laravel-hermes pull request #33
Opened 2021-04-07 15:50 UTC by Highjhacker

## Summary

https://app.clickup.com/t/gb06ee

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-04-08 10:41 UTC, ItsANameToo requested changes

2021-04-08 10:41 UTC, ItsANameToo commented on resources/views/notification-icon.blade.php
> +                        <x-ark-icon name="notifications.danger" size="sm" class="text-theme-danger-400" />
why is this one a different size compared to the others 🤔

2021-04-09 09:16 UTC, Highjhacker commented
@ItsANameToo 
![](https://gyazo.com/4e6511f28475e14e5ea13cf8e8b91a1a.png)

2021-04-09 09:25 UTC, ItsANameToo commented
@Highjhacker missing 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/35610748/114159488-22684d80-9926-11eb-9e51-3b6f3a8a084c.png">
<img width="170" alt="image" src="https://user-images.githubusercontent.com/35610748/114159520-2b591f00-9926-11eb-9d23-58f2167355c5.png">

and the mention one seems to touch the edges of the circle in your screenshot 🤔 may need to be be made a little bit smaller as it's a square icon instead of a round one like the others
<img width="61" alt="image" src="https://user-images.githubusercontent.com/35610748/114159650-4a57b100-9926-11eb-89be-9d9c40f23d51.png">

2021-04-09 14:29 UTC, ItsANameToo approved these changes

2021-04-09 14:29 UTC, merged